In [22]:
import pandas as pd
import seaborn as sb
import numpy as np

from matplotlib import pyplot as plt

from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [14]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [15]:
lb = LabelEncoder()
df['Geography'] = lb.fit_transform(df['Geography'])
df['Gender'] = lb.fit_transform(df['Gender'])

df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,2,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,0,1,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,0,1,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,0,0,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,1,1,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,0,0,28,4,130142.79,1,1,0,38190.78,0

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  int64
 5   Gender           10000 non-null  int64
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(11), str(1)
memory usage: 1.1 MB

In [ ]:
df = df.drop(['RowNumber'],axis=1)
df = df.drop(['CustomerId'],axis=1)
df = df.drop(['Surname'],axis=1)

In [18]:
y = df.pop('Exited')
x = df

In [19]:
y.shape

(10000,)

In [20]:
x.shape

(10000, 10)

In [21]:
x_train,x_test,y_train,y_test = tts(x,y,test_size=.2,random_state=0)

In [ ]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

0.1695817623648747
-2.3045594514691645
-1.1911959052438468
0.03556577994886427
2.05611443791333
1.293254230314501
1.6128308037680645
-0.5417338366124115
-0.1499948110886887
-0.2943197152290076
0.32421558822950225
0.6128653965101402
-0.5829695235096455
1.499432664800671
-0.45926246281794353
-0.22215726315884818
-1.2530494355896977
1.684993255838224
-0.10875912419145471
1.6334486472166814
-0.04690559384560371
1.0149133437581717
0.34483343167811925
-0.2840107935046991
1.5715951168708304
1.9014806120487024
-0.27370187178039057
0.2726709796079598
0.6128653965101402
0.02525685822455577
-0.036596672121295214
-0.9437817838604429
-1.3870654180057083
0.8293527527206186
-1.964365034566984
-0.9850174707576769
0.004639014775938776
-1.2736672790383148
2.05611443791333
0.6231743182344487
0.2108174492621087
-0.6035873669582625
-0.1293769676400717
2.05611443791333
-0.6654408973041135
-0.32524648040193305
-0.8922371752389004
1.6334486472166814
-0.25308402833177357
0.6128653965101402
-0.696367662477039
-0.026287750396986716
0.9736776568609377
0.4891583358184382
-0.01597882867267822
-0.1396858893643802
-1.1396512966223045
2.05611443791333
-1.9025115042211331
-1.2118137486924638
-0.655131975579805
-0.19123049798592268
-0.1396858893643802
-0.01597882867267822
-0.40771785419640105
-1.4489189483515592
1.9633341423945534
0.2005085275378002
-1.9025115042211331
-0.8922371752389004
-0.1396858893643802
0.38606911857535325
1.6643754123896068
-1.5726260090432613
-0.6035873669582625
-1.7169509131835803
0.1695817623648747
0.40668696202397026
-0.24277510660746518
-1.2427405138653893
-0.5829695235096455
1.4478880561791285
0.9427508916880121
-2.067454251810069
0.10772823201902373
-1.0365620793792194
1.087075795828331
1.107693639276948
-0.04690559384560371
1.8293181599785429
-1.0468710011035278
-0.2840107935046991
0.5407029444399807
1.7983913948056174
0.7571903006504591
-0.40771785419640105
-0.1293769676400717
0.30359774478088525
-0.45926246281794353
0.2005085275378002
-1.2530494355896977
2.05611443791333
-0.44895354109363506
-0.10875912419145471
-0.42833569764501805
-2.5313557294039515
0.6231743182344487
-0.716985505925656
0.4891583358184382
-0.47988030626656053
-0.1293769676400717
-1.1911959052438468
-1.232431592141081
-0.5623516800610285
-1.1396512966223045
0.24174421443503422
0.3345245099538108
0.8705884396178526
0.9221330482393951
-0.34586432385055005
-0.07783235901852921
0.12834607546764074
1.375725604108969
-0.861310410065975
0.12834607546764074
1.0149133437581717
-0.6654408973041135
1.6128308037680645
-0.1603037328129972
-0.21184834143453968
0.6334832399587572
-2.046836408361452
-1.9952917997399096
0.9015152047907781
-0.36648216729916705
0.45823157064551273
0.004639014775938776
1.540668351697905
-0.572660601785337
0.6231743182344487
1.623139725492373
0.30359774478088525
-0.9850174707576769
1.499432664800671
0.8293527527206186
-0.36648216729916705
0.12834607546764074
0.8705884396178526
-0.7582211928228899
0.1695817623648747
1.458196977903437
1.6334486472166814
-0.8406925666173579
-0.9231639404118259
-0.27370187178039057
0.6747189268559912
-0.1603037328129972
-1.1499602183466129
-1.4901546352487933
2.05611443791333
-0.613896288682571
-0.026287750396986716
0.7571903006504591
-1.6344795393891123
-1.3458297311084744
-0.9231639404118259
0.2829799013322683
0.5097761792670552
-0.06752343729422072
-0.6860587407527304
0.8396616744449271
0.3551423534024278
1.02522226548248
-1.7891133652537397
1.5097415865249795
-0.8303836448930494
0.38606911857535325
1.2107828565200331
1.272636386865884
-0.09845020246714621
-1.17057806179523
-0.1706126545373057
-0.1190680459157632
0.07680146684609825
0.6231743182344487
0.7881170658233847
-0.27370187178039057
0.7984259875476931
0.38606911857535325
-0.861310410065975
0.7468813789261507
-1.0571799228278365
0.36545127512673625
-0.1706126545373057
-0.9437817838604429
0.9736776568609377
-0.7891479579958155
0.36545127512673625
0.08711038857040675
-1.6550973828377293
-0.8510014883416664
0.9324419699637037
-0.5417338366124115
-0.10875912419145471
-0.5314249148881031
0.9015152047907781
-0.7994568797201239
0.2726709796079598
0.5097761792670552
-1.9849828780156011
-0.05721451556991221
-0.696367662477039
0.7262635354775336
-0.572660601785337
-0.1293769676400717
1.8087003165299258
-0.8922371752389004
-0.5417338366124115
-0.6860587407527304
-0.2633929500560821
1.499432664800671
0.24174421443503422
-0.05721451556991221
1.2829453085901925
-1.1602691400709213
0.13865499719194924
0.12834607546764074
-1.4179921831786337
0.25205313615934277
1.293254230314501
1.561286195146522
1.602521882043756
0.2005085275378002
-1.2736672790383148
-1.6860241480106548
-1.3664475745570912
-1.17057806179523
-0.7582211928228899
0.08711038857040675
0.5097761792670552
0.3963780402996617
0.04587470167317277
-0.9231639404118259
0.09741931029471525
-0.716985505925656
0.9118241265150866
-0.2840107935046991
0.25205313615934277
0.06649254512178975
-0.5829695235096455
0.11803715374333223
-0.18092157626161418
0.34483343167811925
-1.1396512966223045
1.107693639276948
-1.1499602183466129
0.45823157064551273
-0.2633929500560821
1.9839519858431705
1.561286195146522
-0.34586432385055005
-1.5004635569731017
1.2107828565200331
-0.5004981497151775
-0.04690559384560371
-0.8406925666173579
-1.1911959052438468
0.38606911857535325
1.7571557079083835
-0.8406925666173579
1.355107760660352
-0.21184834143453968
0.6541010834073742
-0.3149375586776246
-0.09845020246714621
-1.6860241480106548
-0.9334728621361345
0.47884941409412973
-1.7066419914592716
0.15927284064056624
0.03556577994886427
1.4066523692818944
-0.18092157626161418
-0.04690559384560371
0.15927284064056624
-1.0159442359306023
0.6128653965101402
-0.42833569764501805
-1.7581866000808142
-1.1087245314493788
2.05611443791333
0.5613207878885977
1.272636386865884
1.313872073763118
1.5097415865249795
-1.4489189483515592
1.6746843341139155
0.45823157064551273
1.4375791344548199
0.6953367703046082
-0.1190680459157632
-0.55204275833672
0.38606911857535325
0.9427508916880121
-0.44895354109363506
-1.2736672790383148
0.8912062830664697
0.3139066665051938
0.2108174492621087
0.36545127512673625
0.3551423534024278
-0.510807071439486
1.4478880561791285
1.4685058996277456
0.7365724572018422
0.7159546137532252
0.15927284064056624
-0.32524648040193305
1.6334486472166814
1.004604422033863
-1.2839762007626234
-1.6138616959404952
0.6850278485802996
0.6025564747858317
-0.1706126545373057
0.1798906840891832
-0.2633929500560821
-1.1499602183466129
-0.2633929500560821
0.8087349092720016
0.36545127512673625
-0.5004981497151775
0.1901996058134917
1.148929326174182
-0.696367662477039
0.4685404923698212
0.6747189268559912
0.23143529271072572
0.6644100051316827
-0.1190680459157632
0.8602795178935442
0.3551423534024278
0.5716297096129062
-0.5211159931637945
-0.3561732455748586
0.3139066665051938
-1.1087245314493788
-1.4179921831786337
1.1592382478984906
-0.5829695235096455
-0.9953263924819854
0.3757601968510448
0.32421558822950225
0.23143529271072572
-0.40771785419640105
-0.737603349374273
-1.7478776783565058
-0.572660601785337
-0.42833569764501805
-1.0468710011035278
-1.3561386528327828
-0.04690559384560371
1.087075795828331
-0.490189227990869
-0.23246618488315668
0.5200851009913637
1.8602449251514683
1.7468467861840749
-0.6860587407527304
0.14896391891625774
-1.6344795393891123
-0.7994568797201239
0.03556577994886427
-0.9953263924819854
-1.026253157654911
0.3139066665051938
0.004639014775938776
-1.9334382693940586
-0.6654408973041135
-0.3355554021262416
-0.22215726315884818
-1.5416992438703359
0.32421558822950225
1.767464629632692
0.36545127512673625
-0.9437817838604429
0.1798906840891832
1.6540664906652984
0.8293527527206186
0.34483343167811925
0.1901996058134917
-0.2943197152290076
0.1901996058134917
-0.08814128074283771
-0.593278445233954
-0.32524648040193305
-0.572660601785337
-0.8819282535145919
-0.08814128074283771
-2.3251772949177814
-0.9747085490333685
-0.3561732455748586
-0.19123049798592268
-0.7582211928228899
1.272636386865884
1.0561490306554056
0.2932888230565768
0.5200851009913637
0.3139066665051938
-1.232431592141081
-0.47988030626656053
-1.6860241480106548
-0.42833569764501805
1.0973847175526397
-0.510807071439486
-1.8200401304266651
0.5819386313372147
0.34483343167811925
-1.5416992438703359
-0.22215726315884818
1.396343447557586
0.42730480547258726
-0.7891479579958155
-0.8819282535145919
1.066457952379714
-0.716985505925656
-0.902546096963209
-0.3767910890234756
-0.40771785419640105
0.32421558822950225
2.05611443791333
0.004639014775938776
1.334489917211735
0.24174421443503422
-0.23246618488315668
0.06649254512178975
-0.3149375586776246
0.9221330482393951
0.15927284064056624
-0.34586432385055005
-1.4695367918001763
-1.232431592141081
0.07680146684609825
1.2623274651415755
0.03556577994886427
-1.2942851224869318
-0.9850174707576769
-0.005669906948369721
0.12834607546764074
-1.6860241480106548
1.334489917211735
0.7262635354775336
0.1798906840891832
0.6437921616830656
-1.1190334531736874
-0.22215726315884818
0.2829799013322683
-0.613896288682571
0.8396616744449271
1.4891237430763624
1.107693639276948
2.05611443791333
-1.4179921831786337
-0.1293769676400717
-1.1396512966223045
0.5716297096129062
0.3757601968510448
1.7571557079083835
0.6953367703046082
-0.1603037328129972
-1.2118137486924638
-0.04690559384560371
1.9117895337730109
1.2107828565200331
-1.9334382693940586
0.4685404923698212
0.13865499719194924
0.9427508916880121
-2.170543469053154
-0.44895354109363506
1.5715951168708304
-0.2943197152290076
-0.2633929500560821
1.1386204044498736
0.6334832399587572
1.2829453085901925
0.056183623397481265
-0.6654408973041135
-0.9747085490333685
0.9324419699637037
0.49946725754274673
-0.9334728621361345
0.8293527527206186
-0.6860587407527304
1.9220984554973193
1.2623274651415755
-1.088106688000762
1.9530252206702448
0.2932888230565768
0.8705884396178526
-0.737603349374273
1.02522226548248
0.8087349092720016
0.3963780402996617
-0.46957138454225206
0.1695817623648747
0.23143529271072572
0.7571903006504591
0.8293527527206186
-1.7169509131835803
0.6128653965101402
1.0458401089310971
0.42730480547258726
0.22112637098641721
1.1592382478984906
-0.8716193317902834
0.7159546137532252
0.11803715374333223
0.056183623397481265
0.6850278485802996
-1.8097312087023567
-1.314902965935549
0.8190438309963102
0.30359774478088525
0.6437921616830656
-0.04690559384560371
-1.2015048269681554
0.6334832399587572
0.42730480547258726
-0.6242052104068795
-0.24277510660746518
0.6850278485802996
-0.18092157626161418
0.1901996058134917
1.3447988389360435
1.6643754123896068
-0.2943197152290076
0.2108174492621087
0.9221330482393951
0.10772823201902373
-0.46957138454225206
-1.7375687566321971
0.9530598134123206
-1.1293423748979958
-1.3664475745570912
1.313872073763118
1.1180025610012565
0.7262635354775336
-0.5314249148881031
0.10772823201902373
0.13865499719194924
0.08711038857040675
-0.026287750396986716
-0.19123049798592268
1.02522226548248
0.8912062830664697
-0.42833569764501805
-1.6035527742161868
-0.572660601785337
0.40668696202397026
0.49946725754274673
0.49946725754274673
0.12834607546764074
-0.593278445233954
-0.24277510660746518
-1.0984156097250704
-0.32524648040193305
-0.1603037328129972
1.087075795828331
-0.696367662477039
-0.5211159931637945
1.5509772734222134
0.02525685822455577
-0.47988030626656053
1.107693639276948
-0.27370187178039057
2.05611443791333
0.6541010834073742
0.09741931029471525
0.2829799013322683
-2.046836408361452
-1.7891133652537397
-0.1603037328129972
0.5819386313372147
1.3241809954874264
1.458196977903437
-0.8819282535145919
-0.05721451556991221
-0.7685301145471984
-1.3458297311084744
-0.1603037328129972
-0.634514132131188
-0.510807071439486
-0.30462863695331605
1.5303594299735965
0.6231743182344487
-0.7582211928228899
-0.005669906948369721
-0.45926246281794353
0.49946725754274673
0.7778081440990762
-0.7685301145471984
1.8911716903243938
0.9427508916880121
-0.026287750396986716
0.42730480547258726
-0.036596672121295214
2.05611443791333
-0.45926246281794353
-2.098381016982995
-1.0571799228278365
2.05611443791333
1.3654166823846605
0.25205313615934277
-0.861310410065975
-0.46957138454225206
0.5097761792670552
-0.7994568797201239
-0.8303836448930494
1.5509772734222134
-1.9128204259454418
-1.232431592141081
1.2417096216929586
-0.20153941971023118
-0.40771785419640105
1.1798560913471074
-0.7582211928228899
0.2932888230565768
-0.613896288682571
-0.30462863695331605
-0.696367662477039
-1.6963330697349632
2.05611443791333
-0.9334728621361345
0.7365724572018422
-0.42833569764501805
-1.9334382693940586
0.5303940227156723
-1.2633583573140064
0.04587470167317277
-0.3767910890234756
0.04587470167317277
1.087075795828331
-0.6448230538554965
-0.8922371752389004
0.47884941409412973
0.34483343167811925
1.2004739347957245
-1.8715847390482077
0.9427508916880121
0.7881170658233847
0.6747189268559912
1.788082473081309
-0.06752343729422072
-0.20153941971023118
-1.6654063045620378
0.2726709796079598
-1.5210814004217188
0.07680146684609825
-0.9540907055847514
0.9015152047907781
0.6231743182344487
-0.1293769676400717
0.7984259875476931
-1.2633583573140064
-1.8715847390482077
-0.5829695235096455
0.8293527527206186
0.6128653965101402
-0.42833569764501805
-0.737603349374273
0.8190438309963102
-0.08814128074283771
-0.634514132131188
-0.05721451556991221
0.6437921616830656
0.8396616744449271
0.47884941409412973
0.08711038857040675
0.6334832399587572
0.1695817623648747
-0.10875912419145471
0.7159546137532252
-0.9850174707576769
1.8087003165299258
-1.026253157654911
-0.9643996273090599
0.3551423534024278
0.6850278485802996
1.3447988389360435
0.43761372719689573
-0.005669906948369721
1.2623274651415755
0.5510118661642892
1.5303594299735965
-1.1396512966223045
-0.30462863695331605
1.478814821352054
-0.8303836448930494
0.02525685822455577
-1.9540561128426757
1.2623274651415755
-1.088106688000762
-1.6241706176648036
0.9118241265150866
-0.09845020246714621
0.7365724572018422
0.6437921616830656
-0.6035873669582625
0.34483343167811925
-0.7272944276499644
-0.5417338366124115
-1.0571799228278365
-0.22215726315884818
0.9736776568609377
-1.2942851224869318
-1.5623170873189527
-0.9953263924819854
1.9736430641188618
-1.7891133652537397
-0.19123049798592268
0.7468813789261507
0.5613207878885977
1.0767668741040226
-1.4901546352487933
0.8087349092720016
0.6437921616830656
1.396343447557586
-0.3974089324720925
-1.4283011049029424
-1.9746739562912927
-0.34586432385055005
1.004604422033863
0.2829799013322683
-1.2736672790383148
-1.0571799228278365
1.9633341423945534
-0.675749819028422
-0.9128550186875174
-1.005635314206294
0.1798906840891832
-2.1189988604316117
0.3345245099538108
1.1283114827255651
0.14896391891625774
-1.8097312087023567
-0.6448230538554965
-0.38710001074778405
0.7674992223747676
0.7674992223747676
0.1695817623648747
-0.1396858893643802
-0.6448230538554965
-0.7994568797201239
-0.1499948110886887
-0.675749819028422
-2.4488843556094837
0.1798906840891832
1.4066523692818944
0.6231743182344487
-0.5829695235096455
0.47884941409412973
-1.4798457135244847
0.36545127512673625
-0.655131975579805
2.05611443791333
-0.20153941971023118
-0.9334728621361345
0.004639014775938776
-0.6860587407527304
-0.27370187178039057
0.23143529271072572
-2.160234547328846
-1.1499602183466129
-0.1396858893643802
-1.005635314206294
-0.47988030626656053
-1.9231293476697502
1.623139725492373
0.7056456920289167
-0.10875912419145471
-1.3561386528327828
1.684993255838224
0.24174421443503422
0.4891583358184382
0.1798906840891832
-0.9437817838604429
0.30359774478088525
2.025187672740404
-0.21184834143453968
-0.4180267759207095
-2.088072095258686
-0.510807071439486
-0.737603349374273
0.8190438309963102
-1.3045940442112403
-1.6860241480106548
-0.593278445233954
0.07680146684609825
-1.1087245314493788
0.23143529271072572
1.8396270817028513
0.3139066665051938
-1.4386100266272508
0.43761372719689573
-0.7272944276499644
0.9530598134123206
-0.20153941971023118
0.2829799013322683
2.05611443791333
0.6231743182344487
-1.0365620793792194
-0.5417338366124115
0.2005085275378002
0.5716297096129062
1.870553846875777
0.25205313615934277
-1.0571799228278365
-0.572660601785337
0.9736776568609377
0.8499705961692356
-0.23246618488315668
1.0355311872067885
1.9220984554973193
-1.4489189483515592
-0.05721451556991221
0.6128653965101402
-0.08814128074283771
1.6540664906652984
0.43761372719689573
1.870553846875777
1.7983913948056174
0.9633687351366291
0.6747189268559912
2.05611443791333
0.7365724572018422
0.1901996058134917
-0.22215726315884818
-0.07783235901852921
-0.1499948110886887
0.7159546137532252
0.9324419699637037
-0.3355554021262416
-0.18092157626161418
-1.2530494355896977
0.30359774478088525
-0.593278445233954
0.3139066665051938
-0.005669906948369721
-1.2427405138653893
-1.2530494355896977
-0.23246618488315668
-0.45926246281794353
-1.7478776783565058
0.2726709796079598
1.4375791344548199
1.4272702127305115
1.355107760660352
0.9324419699637037
-0.613896288682571
-0.8819282535145919
1.0767668741040226
0.08711038857040675
0.14896391891625774
-1.1911959052438468
-1.4386100266272508
1.2210917782443416
-0.24277510660746518
-2.2839416080205477
0.7984259875476931
-0.20153941971023118
-0.08814128074283771
1.0767668741040226
1.9014806120487024
1.458196977903437
-0.737603349374273
-0.675749819028422
1.8087003165299258
0.24174421443503422
1.4685058996277456
-0.8303836448930494
0.014947936500247276
0.11803715374333223
-0.22215726315884818
-1.397374339730017
-0.820074723168741
2.05611443791333
0.38606911857535325
1.2210917782443416
-1.17057806179523
0.10772823201902373
-1.2633583573140064
0.5407029444399807
-0.05721451556991221
0.5613207878885977
0.34483343167811925
1.623139725492373
-0.634514132131188
-0.25308402833177357
1.2004739347957245
0.38606911857535325
-1.0365620793792194
0.41699588374827873
0.7881170658233847
-0.634514132131188
0.5716297096129062
0.3345245099538108
-0.36648216729916705
-1.4901546352487933
0.8087349092720016
-0.05721451556991221
0.9118241265150866
1.0355311872067885
-0.9850174707576769
-1.3870654180057083
-2.4695021990581005
0.04587470167317277
0.9839865785852461
0.9633687351366291
-0.036596672121295214
0.6231743182344487
-0.24277510660746518
-0.1706126545373057
-0.634514132131188
-0.2943197152290076
-0.7685301145471984
-1.8509668955995906
-0.4386446193693265
-0.3355554021262416
0.2829799013322683
-0.6860587407527304
0.9324419699637037
1.0561490306554056
0.6747189268559912
-0.490189227990869
-0.7685301145471984
-0.08814128074283771
0.8602795178935442
0.02525685822455577
0.004639014775938776
0.12834607546764074
0.5716297096129062
-0.9334728621361345
0.2932888230565768
0.14896391891625774
-0.21184834143453968
-0.44895354109363506
-0.8097658014444324
-0.06752343729422072
1.4066523692818944
-0.19123049798592268
0.34483343167811925
-1.4179921831786337
-0.20153941971023118
-0.1190680459157632
-1.0984156097250704
-0.4386446193693265
1.0561490306554056
1.0767668741040226
-0.026287750396986716
-0.07783235901852921
0.09741931029471525
-1.8612758173238992
0.15927284064056624
0.3139066665051938
0.8808973613421611
1.0458401089310971
-2.4695021990581005
0.5200851009913637
0.04587470167317277
-1.2530494355896977
0.5303940227156723
-2.500428964231026
-1.6344795393891123
-0.861310410065975
-0.46957138454225206
-2.7581520073387384
-0.2840107935046991
0.32421558822950225
-0.5829695235096455
2.05611443791333
-0.7994568797201239
-0.3767910890234756
-0.21184834143453968
0.004639014775938776
-0.10875912419145471
-0.655131975579805
-2.098381016982995
0.7262635354775336
1.355107760660352
1.3447988389360435
1.2623274651415755
0.7778081440990762
-1.5004635569731017
0.41699588374827873
-1.2427405138653893
-0.1190680459157632
0.3551423534024278
0.42730480547258726
0.8293527527206186
-0.09845020246714621
-1.1293423748979958
-0.6242052104068795
-1.3870654180057083
-1.4695367918001763
-1.4386100266272508
-1.3664475745570912
-0.8406925666173579
-0.5211159931637945
-0.9643996273090599
-1.6757152262863462
1.2107828565200331
0.3345245099538108
0.8190438309963102
1.767464629632692
0.23143529271072572
-0.1396858893643802
2.05611443791333
2.05611443791333