In [1]:
import pandas as pd
import seaborn as sb
import numpy as np

from matplotlib import pyplot as plt

from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [2]:
df = pd.read_csv('Datasets\\Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
lb = LabelEncoder()
df['Geography'] = lb.fit_transform(df['Geography'])
df['Gender'] = lb.fit_transform(df['Gender'])

df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,2,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,0,1,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,0,1,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,0,0,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,1,1,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,0,0,28,4,130142.79,1,1,0,38190.78,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  int64
 5   Gender           10000 non-null  int64
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(11), str(1)
memory usage: 1.1 MB

In [5]:
df = df.drop(['RowNumber'],axis=1)
df = df.drop(['CustomerId'],axis=1)
df = df.drop(['Surname'],axis=1)

In [6]:
y = df.pop('Exited')
x = df

In [7]:
y.shape

(10000,)

In [8]:
x.shape

(10000, 10)

In [9]:
x_train,x_test,y_train,y_test = tts(x,y,test_size=.2,random_state=0)

In [11]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [12]:
x_train

array([[ 0.16958176,  1.51919821, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-2.30455945,  0.3131264 ,  0.91601335, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-1.19119591, -0.89294542, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.9015152 , -0.89294542,  0.91601335, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.62420521,  1.51919821, -1.09168714, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-0.28401079,  0.3131264 , -1.09168714, ...,  0.64259497,
        -1.03227043,  0.32472465]], shape=(8000, 10))

In [13]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

In [14]:
classifier = Sequential()

In [15]:
classifier.add(
    Dense(units=6,kernel_initializer='he_uniform',activation='relu',input_dim=10)
)

c:\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [16]:
classifier.add(
    Dense(units=6,kernel_initializer='he_uniform',activation='relu')
)

In [17]:
classifier.add(
    Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid')
)

In [18]:
classifier.compile(
    optimizer='Adamax',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [19]:
model_history = classifier.fit(x_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 791us/step - accuracy: 0.7759 - loss: 0.5830
Epoch 2/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 811us/step - accuracy: 0.7960 - loss: 0.4942
Epoch 3/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.7960 - loss: 0.4739
Epoch 4/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 769us/step - accuracy: 0.7961 - loss: 0.4606
Epoch 5/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.7977 - loss: 0.4498
Epoch 6/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 820us/step - accuracy: 0.8001 - loss: 0.4418
Epoch 7/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 800us/step - accuracy: 0.8020 - loss: 0.4361
Epoch 8/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 799us/step - accuracy: 0.8016 - loss: 0.4321
Epoch 9/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 794us/step - accuracy: 0.8027 - loss: 0.4287
Epoch 10/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 837us/step - accuracy: 0.8030 - loss: 0.4256
Epoch 11/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 797us/step - accuracy: 0.8040 - loss: 0.4223
Epoch 12/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 829us/step - accuracy: 0.8052 - loss: 0.4189
Epoch 13/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 818us/step - accuracy: 0.8077 - loss: 0.4152
Epoch 14/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 786us/step - accuracy: 0.8087 - loss: 0.4115
Epoch 15/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 800us/step - accuracy: 0.8108 - loss: 0.4075
Epoch 16/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 798us/step - accuracy: 0.8117 - loss: 0.4035
Epoch 17/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 797us/step - accuracy: 0.8136 - loss: 0.3997
Epoch 18/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 859us/step - accuracy: 0.8154 - loss: 0.3963
Epoch 19/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 807us/step - accuracy: 0.8163 - loss: 0.3932
Epoch 20/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 821us/step - accuracy: 0.8171 - loss: 0.3903
Epoch 21/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 834us/step - accuracy: 0.8177 - loss: 0.3877
Epoch 22/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 769us/step - accuracy: 0.8183 - loss: 0.3854
Epoch 23/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 777us/step - accuracy: 0.8186 - loss: 0.3834
Epoch 24/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 790us/step - accuracy: 0.8194 - loss: 0.3817
Epoch 25/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - accuracy: 0.8199 - loss: 0.3801
Epoch 26/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 811us/step - accuracy: 0.8206 - loss: 0.3787
Epoch 27/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.8207 - loss: 0.3775
Epoch 28/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 782us/step - accuracy: 0.8204 - loss: 0.3764
Epoch 29/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 769us/step - accuracy: 0.8210 - loss: 0.3754
Epoch 30/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 773us/step - accuracy: 0.8207 - loss: 0.3746
Epoch 31/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 780us/step - accuracy: 0.8211 - loss: 0.3738
Epoch 32/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 776us/step - accuracy: 0.8209 - loss: 0.3732
Epoch 33/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 773us/step - accuracy: 0.8210 - loss: 0.3726
Epoch 34/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.8214 - loss: 0.3720
Epoch 35/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 776us/step - accuracy: 0.8215 - loss: 0.3715
Epoch 36/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 778us/step - accuracy: 0.8270 - loss: 0.3710
Epoch 37/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.8321 - loss: 0.3706
Epoch 38/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.8330 - loss: 0.3702
Epoch 39/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 780us/step - accuracy: 0.8335 - loss: 0.3699
Epoch 40/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 781us/step - accuracy: 0.8355 - loss: 0.3695
Epoch 41/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 774us/step - accuracy: 0.8356 - loss: 0.3692
Epoch 42/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 769us/step - accuracy: 0.8349 - loss: 0.3688
Epoch 43/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 765us/step - accuracy: 0.8375 - loss: 0.3686
Epoch 44/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 771us/step - accuracy: 0.8384 - loss: 0.3683
Epoch 45/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 759us/step - accuracy: 0.8396 - loss: 0.3681
Epoch 46/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.8399 - loss: 0.3678
Epoch 47/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.8396 - loss: 0.3675
Epoch 48/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - accuracy: 0.8394 - loss: 0.3674
Epoch 49/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 783us/step - accuracy: 0.8396 - loss: 0.3671
Epoch 50/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - accuracy: 0.8395 - loss: 0.3669
Epoch 51/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - accuracy: 0.8400 - loss: 0.3667
Epoch 52/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 774us/step - accuracy: 0.8395 - loss: 0.3666
Epoch 53/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 771us/step - accuracy: 0.8393 - loss: 0.3664
Epoch 54/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 777us/step - accuracy: 0.8399 - loss: 0.3662
Epoch 55/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.8403 - loss: 0.3659
Epoch 56/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 775us/step - accuracy: 0.8395 - loss: 0.3658
Epoch 57/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 777us/step - accuracy: 0.8403 - loss: 0.3655
Epoch 58/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.8394 - loss: 0.3653
Epoch 59/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.8403 - loss: 0.3651
Epoch 60/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 776us/step - accuracy: 0.8407 - loss: 0.3650
Epoch 61/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 765us/step - accuracy: 0.8400 - loss: 0.3648
Epoch 62/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 775us/step - accuracy: 0.8404 - loss: 0.3646
Epoch 63/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 775us/step - accuracy: 0.8403 - loss: 0.3644
Epoch 64/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.8399 - loss: 0.3642
Epoch 65/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 780us/step - accuracy: 0.8411 - loss: 0.3639
Epoch 66/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 768us/step - accuracy: 0.8409 - loss: 0.3638
Epoch 67/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 776us/step - accuracy: 0.8411 - loss: 0.3635
Epoch 68/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.8407 - loss: 0.3633
Epoch 69/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - accuracy: 0.8407 - loss: 0.3631
Epoch 70/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 779us/step - accuracy: 0.8411 - loss: 0.3628
Epoch 71/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.8425 - loss: 0.3626
Epoch 72/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 768us/step - accuracy: 0.8431 - loss: 0.3623
Epoch 73/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - accuracy: 0.8428 - loss: 0.3620
Epoch 74/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.8439 - loss: 0.3617
Epoch 75/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - accuracy: 0.8439 - loss: 0.3614
Epoch 76/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 765us/step - accuracy: 0.8443 - loss: 0.3611
Epoch 77/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 795us/step - accuracy: 0.8456 - loss: 0.3609
Epoch 78/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 775us/step - accuracy: 0.8464 - loss: 0.3606
Epoch 79/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 778us/step - accuracy: 0.8462 - loss: 0.3603
Epoch 80/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 774us/step - accuracy: 0.8471 - loss: 0.3600
Epoch 81/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.8474 - loss: 0.3597
Epoch 82/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 773us/step - accuracy: 0.8466 - loss: 0.3594
Epoch 83/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 776us/step - accuracy: 0.8475 - loss: 0.3591
Epoch 84/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 793us/step - accuracy: 0.8478 - loss: 0.3589
Epoch 85/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - accuracy: 0.8479 - loss: 0.3585
Epoch 86/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.8481 - loss: 0.3583
Epoch 87/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 779us/step - accuracy: 0.8474 - loss: 0.3580
Epoch 88/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 784us/step - accuracy: 0.8487 - loss: 0.3578
Epoch 89/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - accuracy: 0.8485 - loss: 0.3575
Epoch 90/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - accuracy: 0.8487 - loss: 0.3572
Epoch 91/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 773us/step - accuracy: 0.8485 - loss: 0.3569
Epoch 92/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.8479 - loss: 0.3567
Epoch 93/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 768us/step - accuracy: 0.8482 - loss: 0.3564
Epoch 94/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 786us/step - accuracy: 0.8475 - loss: 0.3562
Epoch 95/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 775us/step - accuracy: 0.8484 - loss: 0.3560
Epoch 96/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 762us/step - accuracy: 0.8486 - loss: 0.3557
Epoch 97/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 781us/step - accuracy: 0.8484 - loss: 0.3556
Epoch 98/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 791us/step - accuracy: 0.8500 - loss: 0.3554
Epoch 99/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 781us/step - accuracy: 0.8495 - loss: 0.3552
Epoch 100/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 788us/step - accuracy: 0.8497 - loss: 0.3550

In [20]:
classifier.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 6)              │            66 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 6)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 347 (1.36 KB)

 Trainable params: 115 (460.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 232 (932.00 B)

In [21]:
y_pred = classifier.predict(x_test)
y_pred

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

array([[0.27497944],
       [0.3046609 ],
       [0.16079912],
       ...,
       [0.09591318],
       [0.12798189],
       [0.14199789]], shape=(2000, 1), dtype=float32)

In [25]:
y_pred = (y_pred>.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]], shape=(2000, 1))

In [32]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)[0]

array([1537,   58])

In [34]:
accuracy_score(y_pred,y_test)

0.853

In [35]:
str(round(accuracy_score(y_test,y_pred),4)*100) + '%'

'85.3%'